name: Bug report
description: Something is broken
type: Bug
labels: [bug]
body:
  - type: input
    id: where
    attributes:
      label: Where
      description: app/lib, browser, environment
      placeholder: e.g. web app, Chrome 141, staging
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: If applicable
    validations:
      required: false
